# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "contact-list"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Neill", "Tom Warner", "Paul Bowsher"]
  s.date = "2012-02-14"
  s.description = "Find contacts from multiple providers"
  s.email = ["alex@rawnet.com", "tom@rawnet.com", "paul.bowsher@gmail.com"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/contact_list.rb",
    "lib/contacts.rb",
    "lib/contacts/contact.rb",
    "lib/contacts/contact/facebook.rb",
    "lib/contacts/contact/google.rb",
    "lib/contacts/contact/linkedin.rb",
    "lib/contacts/contact/twitter.rb",
    "lib/contacts/contact/yahoo.rb",
    "lib/contacts/provider.rb",
    "lib/contacts/provider/base.rb",
    "lib/contacts/provider/facebook.rb",
    "lib/contacts/provider/google.rb",
    "lib/contacts/provider/linkedin.rb",
    "lib/contacts/provider/oauth.rb",
    "lib/contacts/provider/oauth2.rb",
    "lib/contacts/provider/twitter.rb",
    "lib/contacts/provider/yahoo.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Find contacts from multiple providers"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<contact-list>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.1.0"])
      s.add_runtime_dependency(%q<multi_json>, ["~> 1.0.4"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.5.0"])
      s.add_runtime_dependency(%q<oauth>, ["~> 0.4.5"])
      s.add_runtime_dependency(%q<oauth2>, ["~> 0.5.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
    else
      s.add_dependency(%q<contact-list>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<activesupport>, [">= 2.1.0"])
      s.add_dependency(%q<multi_json>, ["~> 1.0.4"])
      s.add_dependency(%q<nokogiri>, ["~> 1.5.0"])
      s.add_dependency(%q<oauth>, ["~> 0.4.5"])
      s.add_dependency(%q<oauth2>, ["~> 0.5.2"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<contact-list>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<activesupport>, [">= 2.1.0"])
    s.add_dependency(%q<multi_json>, ["~> 1.0.4"])
    s.add_dependency(%q<nokogiri>, ["~> 1.5.0"])
    s.add_dependency(%q<oauth>, ["~> 0.4.5"])
    s.add_dependency(%q<oauth2>, ["~> 0.5.2"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
  end
end

